name: Simple Workflow

on: [push]

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
      - name: echo a string from command line
        run: echo "A string"
      - name: using an action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
